---
- name: Ensure unzip is installed
  ansible.builtin.include_role:
    name: fastpackages
  vars:
    fastpackages_packages_list:
      - unzip

- name: Setup promtail data directory
  become: True
  ansible.builtin.file:
    state: directory
    dest: "{{ promtail_directory }}"
    owner: root
    group: root
    mode: 0750

- name: Fetch promtail binary
  become: True
  ansible.builtin.get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_directory }}/"
    mode: 0750
  register: new_archive

- name: Unarchive promtail
  become: True
  ansible.builtin.unarchive:
    src: "{{ promtail_directory }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_directory }}/"
    copy: no
  when: new_archive.changed
  notify:
    - Restart promtail

- name: Grant exec bit to promtail binary
  become: True
  ansible.builtin.file:
    dest: "{{ promtail_directory }}/promtail-linux-amd64"
    mode: a+x
  when: new_archive.changed

- name: Setup promtail systemd unit
  become: True
  ansible.builtin.template:
    dest: "/etc/systemd/system/promtail.service"
    src: promtail.service.j2
    owner: root
    group: root
    mode: 0444
  notify:
    - Systemd reload
    - Restart promtail

- name: Configure promtail
  become: True
  ansible.builtin.template:
    dest: '{{ promtail_directory }}/promtail.yml'
    src: 'promtail.yml.j2'
    owner: root
    group: root
    mode: 0440
  notify:
    - Restart promtail
